<main>
    <h1>User List </h1>
    <table>
        <tr>
            <td>Email</td>
            <td>First Name</td>
            <td>Last Name</td>
        </tr>
         <?php foreach($users as $user) {?>
        <tr>
            <td><?=$user -> getEmail()?></td>
            <td><?=$user -> getFirstName()?></td>
            <td><?=$user -> getLastName()?></td>
            <td><a href='index.php?route=show_user&id=<?= $user->getId() ?>'>See More</a></td>
            <td><a href='index.php?route=update_user&id=<?= $user->getId() ?>'>Update User</a></td>
            <td><a href='index.php?route=delete_user&id=<?= $user->getId() ?>'>Delete User</a></td>
        </tr>
        <?php } ?>
    </table>
</main>