<main>
    <table>
        <tr>
            <td>Email</td>
            <td>First Name</td>
            <td>Last Name</td>
        </tr>
         <?php foreach($users as $user) {?>
        <tr>
            <td><?=$user -> getEmail()?></td>
            <td><?=$user -> getFirstName()?></td>
            <td><?=$user -> getLastName(). "<br>" ?></td>
        </tr>
        <?php } ?>
    </table>
</main>