<main>
    <h1>Update User</h1>
    <form method = "post" action="index.php?route=check_update_user" >
        <label for="email">Email</label>
        <input type="text" name="email" id="email"/>
        <label for="first_name">First Name</label>
        <input type="text" name="first_name" id="first_name"/>
        <label for="last_name">Last Name</label>
        <input type="text" name="last_name" id="last_name"/>
        <input type="submit" value="Submit"/>
    </form>
</main>