<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice blog MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=a-propos">À propos</a>
					</li>
					<li>
						<a href="index.php?route=contact">Contact</a>
					</li>
					<li>
						<a href="index.php?route=categorie&categorie=dev-back">Dev-Back</a>
					</li>
					<li>
						<a href="index.php?route=categorie&categorie=dev-front">Dev-Front</a>
					</li>
					<li>
						<a href="index.php?route=article&article=i-love-php">I LOVE PHP</a>
					</li>
					<li>
						<a href="index.php?route=article&article=i-love-js">I LOVE JS</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
		    if($route === "home"){
		    	require "templates/home.phtml";
		    }
		    else if($route === "contact"){
		    	require "templates/contact.phtml";
		    }
		    else if($route === "about"){
		    	require "templates/about.phtml";
		    }
		    else if($route === "notFound"){
		    	require "templates/notFound.phtml";
		    }
		    else if($route === "categorie" && $categorie = "dev-back"){
		    	require "templates/devBack.phtml";
		    }
		    else if($route === "categorie" && $categorie = "dev-front"){
		    	require "templates/devFront.phtml";
		    }
		    else if($route === "article" && $categorie = "i-love-php"){
		    	require "templates/iLovePHP.phtml";
		    }
		    else if($route === "article" && $categorie = "i-love-js"){
		    	require "templates/iLoveJS.phtml";
		    }
		?>
		</body>
</html>