<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice-dark-blue">
<main>
    <section>
        <h2>Vous vous faites rattraper par <br> le werewolf et il vous devore <br><br>DESOLE ( en fait non )</h2>
       
    </section>
    <section>
        <section>
            <img src="assets/img/werewolf.png" />
            <h1>FIN WEREWOLF</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>