<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="<?=$color?>">
<main>
    <section>
        <h2> <?= $choiceShortSentence ?> </h2>
        <div>
             <?php if (count($choices) > 0) { ?>
            <form method="get" action="choices.php">
                
                <input type="hidden" name ="eventNumber" value = "<?= $eventNumber?>"
                
                <?php foreach($choices as $index =>$choice ) { ?>
                
                <div>
                    <input type="radio" id="choice-<?=$index?>" name="choice" value="choice-<?=$index?>">
                    <label for="choice-<?=$index?>"><?=$choice?></label>
                </div>
                
                <?php } ?>
                
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
             <?php } else { ?>
                <a classe = "lienAccueil" href="index.html">Retour à l'accueil</a>
            <?php } ?>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/<?=$eventImage?>" />
            <h1> <?= $eventDescription ?> </h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>