<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <form method="post" action="logic/login.php">
        <label for="email">Email</label>
        <input type="text" name="email" id="email" required="required"/>
        
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required="required"/>
        
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>