<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <form method="post" action = "logic/register.php" >
        <label for="first_name">First Name</label>
        <input type="text" name="first_name" id="first_name" required="required"/>
        
        <label for="last_name">Last Name</label>
        <input type="text" name="last_name" id="last_name" required="required"/>
        
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required="required"/>
        
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required="required"/>
        
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>