<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Verify</title>
</head>
<body>
        <form method="post" action="decrypt_password.php">
            <label for="password">password</label>
            <input type="text" name="password" id="password"/>
            <label for="hash">Hash</label>
            <input type="text" name="hash" id="hash"/>
            <input type="submit" value="Submit"/>
        </form>
</body>
</html>