<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice blog MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">List</a>
					</li>
					<li>
						<a href="index.php?route=create_user">Create</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
		    if($route === "list"){
		    	require "templates/users/list.phtml";
		    }
		    else if($route === "show_user"){
		    	require "templates/users/show.phtml";
		    }
		    else if($route === "create_user"){
		    	require "templates/users/create.phtml";
		    }
		    else if($route === "update_user"){
		    	require "templates/users/update.phtml";
		    }
		?>
		</body>
</html>